Itemname changes
RedGuides/MQ2LinkDB pull request #12
Opened 2024-08-20 01:11 UTC by DerpleMQ2

- Added item names to the link table
- removed the join on the raw data table to fix discovered items not being searchable
- Fixed usage of view_string

2024-08-20 15:48 UTC, dannuic approved these changes

2024-08-20 18:20 UTC, brainiac requested changes
blocking since dan already approved.

I didn't catch this yesterday but you needed to use both the link text and the item name from the ExtractLink result.

You're only using the item name.

2024-08-20 18:20 UTC, brainiac commented on MQ2LinkDBTables.cpp
> +				query = "UPDATE item_links SET link = SUBSTR(link, 1, INSTR(SUBSTR(link, INSTR(link, x'12') + 1), x'12') + INSTR(link, x'12')) WHERE link LIKE '%' || x'12' || '%' || x'12' || '%'";
Reparse the link using ExtractLink, don't do manual string manipulation

2024-08-21 15:14 UTC, brainiac approved these changes

2024-08-21 15:16 UTC, merged